apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki
  namespace: mediawiki
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - front-test.belarus-devops.app
      secretName: front-test.belarus-devops.app
  rules:
    - host: front-test.belarus-devops.app
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: mediawiki-srv
                port:
                  number: 80
