apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameService }}
spec:
  ports:
    - port: {{ .Values.portService }}
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: {{ .Values.type }}
